TriggerEvent('es:addGroupCommand', 'getname', 'user', function(source, args, user)
	TriggerClientEvent("commands:getname", source, tonumber(args[1]))
end, function(source, args, user)
	TriggerClientEvent('chatMessage', source, "SYSTEM", {255, 0, 0}, "Insufficient Permissions.")
end, {help = "Get the player name from server ID", params = {{name = "ID", help = "server id"}}})